import type { Leader } from "@/types";

export const LAYOUT_SEED_LEADERS: Leader[] = [
  {
    id: "ngo-ngoc-du",
    name: "Ngô Ngọc Du",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: "/uploads/portraits/ngo-ngoc-du.jpg",
    homePortraitUrl: "/uploads/portraits/ngo-ngoc-du.jpg",
    detailPortraitUrl: "/uploads/portraits/ngo-ngoc-du.jpg",
    biography: "Thông tin tiểu sử đồng chí Ngô Ngọc Du đang được cập nhật.",
    tier: "bottom",
    sortOrder: 22,
    displaySection: "deputy-1",
    displayOrder: 2,
    timeline: [
      {
        year: "",
        event: "Thứ trưởng Bộ Công an",
        description: "Thứ trưởng Bộ Công an",
        sort: 1,
      },
    ],
    awards: [],
  },
  {
    id: "nguyen-quang-viet",
    name: "Nguyễn Quang Việt",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: "/uploads/portraits/nguyen-quang-viet.jpg",
    homePortraitUrl: "/uploads/portraits/nguyen-quang-viet.jpg",
    detailPortraitUrl: "/uploads/portraits/nguyen-quang-viet.jpg",
    biography: "Thông tin tiểu sử đồng chí Nguyễn Quang Việt đang được cập nhật.",
    tier: "bottom",
    sortOrder: 23,
    displaySection: "deputy-1",
    displayOrder: 3,
    timeline: [
      {
        year: "",
        event: "Thứ trưởng Bộ Công an",
        description: "Thứ trưởng Bộ Công an",
        sort: 1,
      },
    ],
    awards: [],
  },
  {
    id: "nguyen-minh-tien",
    name: "Nguyễn Minh Tiến",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: "/uploads/portraits/nguyen-minh-tien.jpg",
    homePortraitUrl: "/uploads/portraits/nguyen-minh-tien.jpg",
    detailPortraitUrl: "/uploads/portraits/nguyen-minh-tien.jpg",
    biography: "Thông tin tiểu sử đồng chí Nguyễn Minh Tiến đang được cập nhật.",
    tier: "bottom",
    sortOrder: 24,
    displaySection: "deputy-1",
    displayOrder: 9,
    timeline: [
      {
        year: "",
        event: "Thứ trưởng Bộ Công an",
        description: "Thứ trưởng Bộ Công an",
        sort: 1,
      },
    ],
    awards: [],
  },
  {
    id: "lam-van-ta",
    name: "Lâm Văn Tà",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: "/uploads/portraits/lam-van-ta.jpg",
    homePortraitUrl: "/uploads/portraits/lam-van-ta.jpg",
    detailPortraitUrl: "/uploads/portraits/lam-van-ta.jpg",
    biography: "Thông tin tiểu sử đồng chí Lâm Văn Tà đang được cập nhật.",
    tier: "bottom",
    sortOrder: 25,
    displaySection: "deputy-2",
    displayOrder: 1,
    timeline: [
      {
        year: "",
        event: "Thứ trưởng Bộ Công an",
        description: "Thứ trưởng Bộ Công an",
        sort: 1,
      },
    ],
    awards: [],
  },
  {
    id: "dang-hong-duc",
    name: "Đặng Hồng Đức",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: "/uploads/portraits/dang-hong-duc.jpg",
    homePortraitUrl: "/uploads/portraits/dang-hong-duc.jpg",
    detailPortraitUrl: "/uploads/portraits/dang-hong-duc.jpg",
    biography: "Thông tin tiểu sử đồng chí Đặng Hồng Đức đang được cập nhật.",
    tier: "bottom",
    sortOrder: 26,
    displaySection: "deputy-2",
    displayOrder: 9,
    timeline: [
      {
        year: "",
        event: "Thứ trưởng Bộ Công an",
        description: "Thứ trưởng Bộ Công an",
        sort: 1,
      },
    ],
    awards: [],
  },
];
