import type { Leader } from "@/types";

const PLACEHOLDER = (id: string) => `/uploads/portraits/${id}.jpg`;

const bio = (name: string) =>
  `Đồng chí ${name} có nhiều năm công tác trong lực lượng Công an nhân dân, góp phần bảo đảm an ninh quốc gia, giữ vững trật tự an toàn xã hội.`;

const timeline = (year: string, event: string) => ({
  year,
  event,
  description: event,
});

/** 24 lãnh đạo theo bố cục màn hình 55 inch — upload ảnh tại /uploads/portraits/{id}.jpg */
export const SAMPLE_LEADERS: Leader[] = [
  {
    id: "pham-hung",
    name: "Phạm Hùng",
    position: "Ủy viên Bộ Chính trị\nChủ tịch Hội đồng Bộ trưởng",
    portraitUrl: PLACEHOLDER("pham-hung"),
    biography: bio("Phạm Hùng"),
    tier: "top",
    sortOrder: 1,
    timeline: [],
  },
  {
    id: "to-lam",
    name: "Tô Lâm",
    position:
      "TC trưởng TC An ninh\nThứ trưởng, Bộ trưởng Bộ CA\nUV Bộ Chính trị khóa XII, XIII\nChủ tịch nước & Tổng Bí thư BCH TW Đảng khóa XIII (2024 - Nay)",
    portraitUrl: PLACEHOLDER("to-lam"),
    biography: bio("Tô Lâm"),
    tier: "top",
    sortOrder: 2,
    timeline: [timeline("2024", "Tổng Bí thư BCH Trung ương Đảng")],
  },
  {
    id: "pham-minh-chinh",
    name: "Phạm Minh Chính",
    position:
      "P.TC trưởng TC V (2006)\nTC trưởng TC IV (2010)\nThứ trưởng Bộ CA (2010-2011)\nThủ tướng Chính phủ",
    portraitUrl: PLACEHOLDER("pham-minh-chinh"),
    biography: bio("Phạm Minh Chính"),
    tier: "top",
    sortOrder: 3,
    timeline: [timeline("2021", "Thủ tướng Chính phủ")],
  },
  {
    id: "tran-dai-quang",
    name: "Trần Đại Quang",
    position:
      "P.TC trưởng TC An ninh\nThứ trưởng, Bộ trưởng Bộ CA\nUV Bộ Chính trị khóa XI, XII\nChủ tịch nước CHXHCN Việt Nam (2016-2018)",
    portraitUrl: PLACEHOLDER("tran-dai-quang"),
    biography: bio("Trần Đại Quang"),
    tier: "top",
    sortOrder: 4,
    timeline: [timeline("2016", "Chủ tịch nước")],
  },
  {
    id: "le-gian",
    name: "Lê Giản",
    position: "Tổng Giám đốc Nha Công an",
    portraitUrl: PLACEHOLDER("le-gian"),
    biography: bio("Lê Giản"),
    tier: "bottom",
    sortOrder: 1,
    timeline: [],
  },
  {
    id: "tran-quoc-hoan",
    name: "Trần Quốc Hoàn",
    position: "Bộ trưởng Bộ Công an",
    portraitUrl: PLACEHOLDER("tran-quoc-hoan"),
    biography: bio("Trần Quốc Hoàn"),
    tier: "bottom",
    sortOrder: 2,
    timeline: [],
  },
  {
    id: "mai-chi-tho",
    name: "Mai Chí Thọ",
    position: "Bộ trưởng Bộ Nội vụ",
    portraitUrl: PLACEHOLDER("mai-chi-tho"),
    biography: bio("Mai Chí Thọ"),
    tier: "bottom",
    sortOrder: 3,
    timeline: [],
  },
  {
    id: "bui-thien-ngo",
    name: "Bùi Thiện Ngộ",
    position:
      "P.TC trưởng TC ANND (1985)\nUV Bộ Chính trị Khóa VII\nBộ trưởng Bộ NV (1991-1996)",
    portraitUrl: PLACEHOLDER("bui-thien-ngo"),
    biography: bio("Bùi Thiện Ngộ"),
    tier: "bottom",
    sortOrder: 4,
    timeline: [timeline("1985", "Phó Tổng cục trưởng TC ANND")],
  },
  {
    id: "le-minh-huong",
    name: "Lê Minh Hương",
    position:
      "P.TC trưởng, TC trưởng TC Tình báo (1988-1990)\nUV Bộ Chính trị khóa VII, IX\nBộ trưởng Bộ NV (1996-2002)",
    portraitUrl: PLACEHOLDER("le-minh-huong"),
    biography: bio("Lê Minh Hương"),
    tier: "bottom",
    sortOrder: 5,
    timeline: [timeline("1996", "Bộ trưởng Bộ Nội vụ")],
  },
  {
    id: "le-hong-anh",
    name: "Lê Hồng Anh",
    position: "Bộ trưởng Bộ Công an\nUV Bộ Chính trị",
    portraitUrl: PLACEHOLDER("le-hong-anh"),
    biography: bio("Lê Hồng Anh"),
    tier: "bottom",
    sortOrder: 6,
    timeline: [],
  },
  {
    id: "luong-tam-quang",
    name: "Lương Tam Quang",
    position:
      "Thứ trưởng Bộ CA (2019)\nUV TW Đảng Khóa XIII\nBộ trưởng Bộ CA (2024)\nUV Bộ Chính trị khóa XIII",
    portraitUrl: PLACEHOLDER("luong-tam-quang"),
    biography: bio("Lương Tam Quang"),
    tier: "bottom",
    sortOrder: 7,
    timeline: [timeline("2024", "Bộ trưởng Bộ Công an")],
  },
  {
    id: "le-quoc-than",
    name: "Lê Quốc Thân",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: PLACEHOLDER("le-quoc-than"),
    biography: bio("Lê Quốc Thân"),
    tier: "bottom",
    sortOrder: 8,
    timeline: [],
  },
  {
    id: "tran-quyet",
    name: "Trần Quyết",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: PLACEHOLDER("tran-quyet"),
    biography: bio("Trần Quyết"),
    tier: "bottom",
    sortOrder: 9,
    timeline: [],
  },
  {
    id: "vien-chi",
    name: "Viễn Chi",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: PLACEHOLDER("vien-chi"),
    biography: bio("Viễn Chi"),
    tier: "bottom",
    sortOrder: 10,
    timeline: [],
  },
  {
    id: "hoang-thao",
    name: "Hoàng Thao",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: PLACEHOLDER("hoang-thao"),
    biography: bio("Hoàng Thao"),
    tier: "bottom",
    sortOrder: 11,
    timeline: [],
  },
  {
    id: "cao-dang-chiem",
    name: "Cao Đăng Chiếm",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: PLACEHOLDER("cao-dang-chiem"),
    biography: bio("Cao Đăng Chiếm"),
    tier: "bottom",
    sortOrder: 12,
    timeline: [],
  },
  {
    id: "nguyen-tai",
    name: "Nguyễn Tài",
    position: "Thứ trưởng Bộ Công an",
    portraitUrl: PLACEHOLDER("nguyen-tai"),
    biography: bio("Nguyễn Tài"),
    tier: "bottom",
    sortOrder: 13,
    timeline: [],
  },
  {
    id: "vo-viet-thanh",
    name: "Võ Viết Thanh",
    position: "TC trưởng TC ANND (1988)\nThứ trưởng Bộ NV (1988-1991)",
    portraitUrl: PLACEHOLDER("vo-viet-thanh"),
    biography: bio("Võ Viết Thanh"),
    tier: "bottom",
    sortOrder: 14,
    timeline: [timeline("1988", "Tổng cục trưởng TC ANND")],
  },
  {
    id: "nguyen-khanh-toan",
    name: "Nguyễn Khánh Toàn",
    position:
      "TC trưởng TC ANND (1989)\nThứ trưởng Bộ CA (1996)\nThứ trưởng Thường trực Bộ CA (1998-2011)",
    portraitUrl: PLACEHOLDER("nguyen-khanh-toan"),
    biography: bio("Nguyễn Khánh Toàn"),
    tier: "bottom",
    sortOrder: 15,
    timeline: [timeline("1996", "Thứ trưởng Bộ Công an")],
  },
  {
    id: "bui-van-nam",
    name: "Bùi Văn Nam",
    position:
      "P.TC trưởng, TC trưởng TC ANND (1989)\nThứ trưởng Bộ CA (1996)\nThứ trưởng Thường trực Bộ CA (1998-2011) - (2013-2021)",
    portraitUrl: PLACEHOLDER("bui-van-nam"),
    biography: bio("Bùi Văn Nam"),
    tier: "bottom",
    sortOrder: 18,
    timeline: [timeline("1996", "Thứ trưởng Bộ Công an")],
  },
  {
    id: "nguyen-van-huong",
    name: "Nguyễn Văn Hưởng",
    position: "TC trưởng TC An ninh (1997)\nThứ trưởng Bộ CA (2001-2011)",
    portraitUrl: PLACEHOLDER("nguyen-van-huong"),
    biography: bio("Nguyễn Văn Hưởng"),
    tier: "bottom",
    sortOrder: 16,
    timeline: [timeline("2001", "Thứ trưởng Bộ Công an")],
  },
  {
    id: "thi-van-tam",
    name: "Thi Văn Tám",
    position: "TC trưởng TC An ninh (2001)\nThứ trưởng Bộ CA (2006-2008)",
    portraitUrl: PLACEHOLDER("thi-van-tam"),
    biography: bio("Thi Văn Tám"),
    tier: "bottom",
    sortOrder: 17,
    timeline: [timeline("2006", "Thứ trưởng Bộ Công an")],
  },
  {
    id: "pham-dung",
    name: "Phạm Dũng",
    position:
      "TC trưởng TC ANND (2008-2009)\nTC trưởng TC An ninh II (2010)\nThứ trưởng Bộ NV kiêm Trưởng Ban TGCP (2012)\nThứ trưởng Bộ CA (2015-2017)",
    portraitUrl: PLACEHOLDER("pham-dung"),
    biography: bio("Phạm Dũng"),
    tier: "bottom",
    sortOrder: 19,
    timeline: [timeline("2015", "Thứ trưởng Bộ Công an")],
  },
  {
    id: "pham-the-tung",
    name: "Phạm Thế Tùng",
    position:
      "Cục trưởng Cục ANCT nội bộ (12/2023)\nThứ trưởng Bộ CA (7/2024)",
    portraitUrl: PLACEHOLDER("pham-the-tung"),
    biography: bio("Phạm Thế Tùng"),
    tier: "bottom",
    sortOrder: 20,
    timeline: [timeline("2024", "Thứ trưởng Bộ Công an")],
  },
];
